### ISSUE TITLE
Phrase update

### ISSUE THREAD

**Issue by khikmatullaev** [navatech/yii2-multi-language#3]
While using your extension I came to the conclusion that it will be nice to use in phrases parameters like:

Traslate::my_site('Home', '2')

The result will be: :"My Home in in the 2 flow", where 'Home' and '2' are passed as parameters.
What do you think about it?

**Comment by phuong17889** [comment]
Yes, but I think you can use it as:
Your phrase: `My {1} in the {2} floor`
and your code `echo Translate::my_site(['Home', 'third']);` will be `My Home in the third floor`

**Comment by khikmatullaev** [comment]
Yes, it works! Thanks you a lot!
